PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org:        <http://www.w3.org/ns/org#>
PREFIX meemoo:     <https://meemoo.be/ns/org#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX graphs: <https://data.meemoo.be/graphs/>
PREFIX source: <https://data.meemoo.be/sources/>

#WITH graphs:organizations
INSERT {
    GRAPH graphs:organizations {
        ?org a meemoo:EducationalOrganization.      
    } 
}
USING graphs:ldap_organizations
USING graphs:ldap_entities
WHERE {
    # Organization
    ?o source:objectClass "x-be-viaa-educationalOrganization";
    source:o ?orid;

    BIND (URI(CONCAT('http://data.meemoo.be/organizations/', ?orid)) AS ?org)
}