PREFIX mh:  <https://meemoo.be/ns/mh#> 
PREFIX graphs: <https://data.meemoo.be/graphs/>

INSERT DATA {
GRAPH graphs:organizations {
<https://data.meemoo.be/organizations/OR-4x54g1p>
        mh:label  "advn" .

<https://data.meemoo.be/organizations/OR-fx73x54>
        mh:label  "algemeenrijksarchief" .

<https://data.meemoo.be/organizations/OR-154dn75>
        mh:label  "amsab" .

<https://data.meemoo.be/organizations/OR-wd3q12h>
        mh:label  "amvb" .

<https://data.meemoo.be/organizations/OR-j38kh0h>
        mh:label  "antigone" .

<https://data.meemoo.be/organizations/OR-jq0st8z>
        mh:label  "apa" .

<https://data.meemoo.be/organizations/OR-rn30682>
        mh:label  "argos" .

<https://data.meemoo.be/organizations/OR-mw28d4m>
        mh:label  "atv" .

<https://data.meemoo.be/organizations/OR-db7vp75>
        mh:label  "atwodogscompany" .

<https://data.meemoo.be/organizations/OR-h41jm06>
        mh:label  "avs" .

<https://data.meemoo.be/organizations/OR-1r6n061>
        mh:label  "bakkerijmuseum" .

<https://data.meemoo.be/organizations/OR-5h7bt0f>
        mh:label  "bokrijk" .

<https://data.meemoo.be/organizations/OR-pr7mt1r>
        mh:label  "campo" .

<https://data.meemoo.be/organizations/OR-fx73x4x>
        mh:label  "cegesoma" .

<https://data.meemoo.be/organizations/OR-pz51k8v>
        mh:label  "ciedekoe" .

<https://data.meemoo.be/organizations/OR-222r55b>
        mh:label  "circuscentrum" .

<https://data.meemoo.be/organizations/OR-th8bm56>
        mh:label  "compagniececilia" .

<https://data.meemoo.be/organizations/OR-k93157z>
        mh:label  "compagnietartaren" .

<https://data.meemoo.be/organizations/OR-th8bm6d>
        mh:label  "compmarius" .

<https://data.meemoo.be/organizations/OR-gx44t48>
        mh:label  "cultureelerfgoedannuntiaten" .

<https://data.meemoo.be/organizations/OR-z892d9n>
        mh:label  "damagedgoods" .

<https://data.meemoo.be/organizations/OR-154dn8c>
        mh:label  "demaan" .

<https://data.meemoo.be/organizations/OR-x63b475>
        mh:label  "denast" .

<https://data.meemoo.be/organizations/OR-3x83k2j>
        mh:label  "departementcultuurjeugdenmedia" .

<https://data.meemoo.be/organizations/OR-h41jm2m>
        mh:label  "departementkanselarijenbestuur" .

<https://data.meemoo.be/organizations/OR-rn30698>
        mh:label  "departementmobiliteitenopenbarewerken" .

<https://data.meemoo.be/organizations/OR-7p8tc73>
        mh:label  "departementonderwijsenvorming" .

<https://data.meemoo.be/organizations/OR-fj29c3h>
        mh:label  "deroovers" .

<https://data.meemoo.be/organizations/OR-cc0ts6n>
        mh:label  "designmuseumgent" .

<https://data.meemoo.be/organizations/OR-610vr4b>
        mh:label  "desingel" .

<https://data.meemoo.be/organizations/OR-6h4cq0s>
        mh:label  "dewereldvankina" .

<https://data.meemoo.be/organizations/OR-2804z00>
        mh:label  "eastman" .

<https://data.meemoo.be/organizations/OR-v97zq9j>
        mh:label  "erfgoedbibliotheekhendrikconscience" .

<https://data.meemoo.be/organizations/OR-vm42x0f>
        mh:label  "erfgoedcelbrussel" .

<https://data.meemoo.be/organizations/OR-qz22g86>
        mh:label  "erfgoedcelco7" .

<https://data.meemoo.be/organizations/OR-5x25c3f>
        mh:label  "erfgoedceldenderland" .

<https://data.meemoo.be/organizations/OR-2804z16>
        mh:label  "erfgoedcelkempenskarakter" .

<https://data.meemoo.be/organizations/OR-zc7rt4f>
        mh:label  "erfgoedcelkerf" .

<https://data.meemoo.be/organizations/OR-m61bp50>
        mh:label  "erfgoedcelkusterfgoed" .

<https://data.meemoo.be/organizations/OR-445hb8c>
        mh:label  "erfgoedcellandvandendermonde" .

<https://data.meemoo.be/organizations/OR-pz51k92>
        mh:label  "erfgoedcelleieschelde" .

<https://data.meemoo.be/organizations/OR-0c4sj54>
        mh:label  "erfgoedcelleuven" .

<https://data.meemoo.be/organizations/OR-cn6xz63>
        mh:label  "erfgoedcelmeetjesland" .

<https://data.meemoo.be/organizations/OR-348gf97>
        mh:label  "erfgoedcelmijnerfgoed" .

<https://data.meemoo.be/organizations/OR-bn9x26w>
        mh:label  "erfgoedcelpajottenlandzennevallei" .

<https://data.meemoo.be/organizations/OR-k649s4f>
        mh:label  "erfgoedcelterf" .

<https://data.meemoo.be/organizations/OR-tq5rd29>
        mh:label  "erfgoedcelwaasland" .

<https://data.meemoo.be/organizations/OR-hd7ns1v>
        mh:label  "erfgoednoorderkempen" .

<https://data.meemoo.be/organizations/OR-7w6752w>
        mh:label  "erfgoedviersprong" .

<https://data.meemoo.be/organizations/OR-gf0mw0b>
        mh:label  "erfgoedzuidwest" .

<https://data.meemoo.be/organizations/OR-xg9f96d>
        mh:label  "fabuleus" .

<https://data.meemoo.be/organizations/OR-jw86m54>
        mh:label  "felixarchief" .

<https://data.meemoo.be/organizations/OR-2r3nw67>
        mh:label  "felixartmuseum" .

<https://data.meemoo.be/organizations/OR-kh0dz3q>
        mh:label  "focus-wtv" .

<https://data.meemoo.be/organizations/OR-pg1hn2h>
        mh:label  "fomu" .

<https://data.meemoo.be/organizations/OR-8s4jn9m>
        mh:label  "greatinvestment" .

<https://data.meemoo.be/organizations/OR-z60c17h>
        mh:label  "grep" .

<https://data.meemoo.be/organizations/OR-p26q312>
        mh:label  "hetgevolg" .

<https://data.meemoo.be/organizations/OR-bk16p3h>
        mh:label  "hetnieuwstedelijk" .

<https://data.meemoo.be/organizations/OR-sn0138d>
        mh:label  "hetpaleis" .

<https://data.meemoo.be/organizations/OR-4f1mh8v>
        mh:label  "hofvanbusleyden" .

<https://data.meemoo.be/organizations/OR-1v5bc86>
        mh:label  "huisvanalijn" .

<https://data.meemoo.be/organizations/OR-7p8tc5p>
        mh:label  "iff" .

<https://data.meemoo.be/organizations/OR-4m9193m>
        mh:label  "jenevermuseum" .

<https://data.meemoo.be/organizations/OR-1n7xm3h>
        mh:label  "kaap" .

<https://data.meemoo.be/organizations/OR-057cr7t>
        mh:label  "kasteelvangaasbeek" .

<https://data.meemoo.be/organizations/OR-r785n68>
        mh:label  "kbr" .

<https://data.meemoo.be/organizations/OR-vd6p425>
        mh:label  "kca" .

<https://data.meemoo.be/organizations/OR-d50fx1d>
        mh:label  "koers" .

<https://data.meemoo.be/organizations/OR-b56d422>
        mh:label  "koninklijkebibliotheek" .

<https://data.meemoo.be/organizations/OR-6d5p979>
        mh:label  "koninklijkmuseumvanhetleger" .

<https://data.meemoo.be/organizations/OR-dj58g2z>
        mh:label  "kopergietery" .

<https://data.meemoo.be/organizations/OR-3x83k1b>
        mh:label  "kuleuvenkadoc" .

<https://data.meemoo.be/organizations/OR-ff3m004>
        mh:label  "kuleuvenlimel" .

<https://data.meemoo.be/organizations/OR-gh9b857>
        mh:label  "kuleuvenuniversiteitsbibliotheek" .

<https://data.meemoo.be/organizations/OR-k06x07c>
        mh:label  "kunstenfestivaldesarts" .

<https://data.meemoo.be/organizations/OR-ms3k117>
        mh:label  "kunstenpunt" .

<https://data.meemoo.be/organizations/OR-ns0kx2n>
        mh:label  "kunstwerk" .

<https://data.meemoo.be/organizations/OR-wh2dd63>
        mh:label  "lesballetscdelab" .

<https://data.meemoo.be/organizations/OR-kw57h48>
        mh:label  "letterenhuis" .

<https://data.meemoo.be/organizations/OR-g44hq0v>
        mh:label  "liberaalarchief" .

<https://data.meemoo.be/organizations/OR-rv0d055>
        mh:label  "lod" .

<https://data.meemoo.be/organizations/OR-x921j0n>
        mh:label  "lukasweb" .

<https://data.meemoo.be/organizations/OR-h98zc6z>
        mh:label  "marthatentatief" .

<https://data.meemoo.be/organizations/OR-6q1sg5c>
        mh:label  "mas" .

<https://data.meemoo.be/organizations/OR-gq6r19m>
        mh:label  "medialaan" .

<https://data.meemoo.be/organizations/OR-ks6j41w>
        mh:label  "memorialmuseumpasschendaele1917" .

<https://data.meemoo.be/organizations/OR-bg2h89t>
        mh:label  "mhka" .

<https://data.meemoo.be/organizations/OR-2z12p11>
        mh:label  "miat" .

<https://data.meemoo.be/organizations/OR-z60c169>
        mh:label  "middelheim" .

<https://data.meemoo.be/organizations/OR-8c9r36r>
        mh:label  "modemuseumhasselt" .

<https://data.meemoo.be/organizations/OR-td9n72t>
        mh:label  "momu" .

<https://data.meemoo.be/organizations/no-external-id>
        mh:label  "monitor" .

<https://data.meemoo.be/organizations/OR-pn8xd88>
        mh:label  "msk" .

<https://data.meemoo.be/organizations/OR-jw86m4x>
        mh:label  "museabrugge" .

<https://data.meemoo.be/organizations/OR-np1wh95>
        mh:label  "museaizegem" .

<https://data.meemoo.be/organizations/OR-qr4nq29>
        mh:label  "museumdemindere" .

<https://data.meemoo.be/organizations/OR-sf2mb3q>
        mh:label  "museumdhondt-dhaenens" .

<https://data.meemoo.be/organizations/OR-f766631>
        mh:label  "museumdrguislain" .

<https://data.meemoo.be/organizations/OR-d21rh8x>
        mh:label  "museumedelsmeedkunstjuwelenendiamant" .

<https://data.meemoo.be/organizations/OR-hx15q4m>
        mh:label  "museumvandeinzeendeleiestreek" .

<https://data.meemoo.be/organizations/OR-9g5gc9g>
        mh:label  "muzee" .

<https://data.meemoo.be/organizations/OR-7s7hr82>
        mh:label  "muziektheatertransparant" .

<https://data.meemoo.be/organizations/OR-x63b48c>
        mh:label  "navigo" .

<https://data.meemoo.be/organizations/OR-416sz5v>
        mh:label  "needcompany" .

<https://data.meemoo.be/organizations/OR-0c4sj4x>
        mh:label  "ntgent" .

<https://data.meemoo.be/organizations/OR-fb4wk7h>
        mh:label  "ontroerendgoed" .

<https://data.meemoo.be/organizations/OR-1j9772n>
        mh:label  "openbarebibliotheekbrugge" .

<https://data.meemoo.be/organizations/OR-cr5nb9m>
        mh:label  "operaballetvanvlaanderen" .

<https://data.meemoo.be/organizations/OR-vx0628j>
        mh:label  "plantentuinmeise" .

<https://data.meemoo.be/organizations/OR-ft8dj2r>
        mh:label  "provinciaalarchiefwestvlaanderen" .

<https://data.meemoo.be/organizations/OR-z31nn3s>
        mh:label  "provincialebibliotheeklimburg" .

<https://data.meemoo.be/organizations/OR-g15t97c>
        mh:label  "provincialebibliotheektolhuis" .

<https://data.meemoo.be/organizations/OR-dn3zv92>
        mh:label  "redstarlinemuseum" .

<https://data.meemoo.be/organizations/OR-1z41s1p>
        mh:label  "ringtv" .

<https://data.meemoo.be/organizations/OR-222r544>
        mh:label  "rmm" .

<https://data.meemoo.be/organizations/OR-x63b46z>
        mh:label  "rob" .

<https://data.meemoo.be/organizations/OR-6t0gw08>
        mh:label  "robin" .

<https://data.meemoo.be/organizations/OR-1r6n05t>
        mh:label  "rosas" .

<https://data.meemoo.be/organizations/OR-sf2mb2h>
        mh:label  "rtv" .

<https://data.meemoo.be/organizations/OR-7940t31>
        mh:label  "sbs" .

<https://data.meemoo.be/organizations/OR-vm42w94>
        mh:label  "sering" .

<https://data.meemoo.be/organizations/OR-np1wh8z>
        mh:label  "smak" .

<https://data.meemoo.be/organizations/OR-j09w371>
        mh:label  "sportimonium" .

<https://data.meemoo.be/organizations/OR-cv4br1w>
        mh:label  "stadsarchiefbrugge" .

<https://data.meemoo.be/organizations/OR-mp4vm8m>
        mh:label  "stadsarchiefdiest" .

<https://data.meemoo.be/organizations/OR-d50fx06>
        mh:label  "stadsarchiefenhidocdendermonde" .

<https://data.meemoo.be/organizations/OR-f47gt0h>
        mh:label  "stadsarchiefgent" .

<https://data.meemoo.be/organizations/OR-x05xc02>
        mh:label  "stadsarchiefieper" .

<https://data.meemoo.be/organizations/OR-9c6s063>
        mh:label  "stadsarchiefkortrijk" .

<https://data.meemoo.be/organizations/OR-tx35586>
        mh:label  "stadsarchiefmechelen" .

<https://data.meemoo.be/organizations/OR-db7vp8c>
        mh:label  "stadsarchiefpoperinge" .

<https://data.meemoo.be/organizations/OR-4x54g33>
        mh:label  "stadsarchiefroeselare" .

<https://data.meemoo.be/organizations/OR-c53f100>
        mh:label  "stadsarchiefsint-niklaas" .

<https://data.meemoo.be/organizations/OR-8p5v867>
        mh:label  "stadsarchieftielt" .

<https://data.meemoo.be/organizations/OR-9k45s4c>
        mh:label  "stadsarchieftongeren" .

<https://data.meemoo.be/organizations/OR-7d2q67n>
        mh:label  "stadsarchiefturnhout" .

<https://data.meemoo.be/organizations/OR-b56d41v>
        mh:label  "stadsarchiefwaregem" .

<https://data.meemoo.be/organizations/OR-kk94b7d>
        mh:label  "stadsbibliotheekkortrijk" .

<https://data.meemoo.be/organizations/OR-hq3rx9t>
        mh:label  "stadsmuseumlokeren" .

<https://data.meemoo.be/organizations/OR-5h7bs94>
        mh:label  "stam" .

<https://data.meemoo.be/organizations/OR-qv3c35t>
        mh:label  "stan" .

<https://data.meemoo.be/organizations/OR-9g5gd0s>
        mh:label  "stedelijkmuseumhoogstraten" .

<https://data.meemoo.be/organizations/OR-z892f0z>
        mh:label  "studioorka" .

<https://data.meemoo.be/organizations/OR-gb1xg6n>
        mh:label  "tarsenaal" .

<https://data.meemoo.be/organizations/OR-h41jm1d>
        mh:label  "testbeeld" .

<https://data.meemoo.be/organizations/OR-319s24f>
        mh:label  "theateraanzee" .

<https://data.meemoo.be/organizations/OR-bk16p29>
        mh:label  "theaterdespiegel" .

<https://data.meemoo.be/organizations/OR-6t0gv9z>
        mh:label  "theatermalpertuis" .

<https://data.meemoo.be/organizations/OR-348gf81>
        mh:label  "theaterstap" .

<https://data.meemoo.be/organizations/OR-tm7209x>
        mh:label  "theaterzuidpool" .

<https://data.meemoo.be/organizations/OR-pv6b648>
        mh:label  "toneelhuis" .

<https://data.meemoo.be/organizations/OR-sf2mb4x>
        mh:label  "troubleynjanfabre" .

<https://data.meemoo.be/organizations/OR-416sz62>
        mh:label  "tuningpeople" .

<https://data.meemoo.be/organizations/OR-5t3fz9m>
        mh:label  "tuttifratelli" .

<https://data.meemoo.be/organizations/OR-d79593p>
        mh:label  "tvbxl" .

<https://data.meemoo.be/organizations/OR-4q7qp5p>
        mh:label  "tvlimburg" .

<https://data.meemoo.be/organizations/OR-8g8fg94>
        mh:label  "tvoost" .

<https://data.meemoo.be/organizations/OR-0z70w1b>
        mh:label  "ugent" .

<https://data.meemoo.be/organizations/OR-9k45s35>
        mh:label  "ultimavez" .

<https://data.meemoo.be/organizations/OR-w66976m>
        mh:label  "viaa" .

<https://data.meemoo.be/organizations/OR-bz61758>
        mh:label  "viaa-archief" .

<https://data.meemoo.be/organizations/OR-5q4rk67>
        mh:label  "villanella" .

<https://data.meemoo.be/organizations/OR-mw28d5t>
        mh:label  "vlaamselandmaatschappij" .

<https://data.meemoo.be/organizations/OR-7s7hs0k>
        mh:label  "vlaamsemaatschappijvoorsociaalwonen" .

<https://data.meemoo.be/organizations/OR-7h1dk9t>
        mh:label  "vlaamsparlement" .

<https://data.meemoo.be/organizations/OR-086351n>
        mh:label  "voetvolk" .

<https://data.meemoo.be/organizations/OR-rf5kf25>
        mh:label  "vrt" .

<https://data.meemoo.be/organizations/OR-251fj8q>
        mh:label  "walpurgis" .

<https://data.meemoo.be/organizations/OR-xd0qx2q>
        mh:label  "wpzimmer" .

<https://data.meemoo.be/organizations/OR-5t3fz8d>
        mh:label  "zeticon" .

<https://data.meemoo.be/organizations/OR-513tv6d>
        mh:label  "zomervanantwerpen" .

}}