PREFIX mh:     <https://data.hetarchief.be/ns/mediahaven/>

CONSTRUCT {
    ?org mh:label ?Name      
}
WHERE {
  BIND (URI(CONCAT('https://data.hetarchief.be/id/organization/', ?ExternalId)) AS ?org)
}